---
- name: Collect Installed Software from Kali Linux Systems
  hosts: linux
  become: yes
  gather_facts: no

  tasks:
    - name: Get list of installed packages
      shell: dpkg-query -W -f='${binary:Package},${Version},${Architecture}\n'
      register: installed_software

    - name: Save installed packages to a YAML file
      copy:
        content: |
          {% for line in installed_software.stdout_lines %}
          - name: {{ line.split(',')[0] }}
            version: {{ line.split(',')[1] }}
            arch: {{ line.split(',')[2] }}
          {% endfor %}
        dest: /tmp/software_inventory_kali.yaml
        mode: '0644'

    - name: Show where the YAML file is stored
      debug:
        msg: "Software inventory saved to /tmp/software_inventory_kali.yaml"
