- name: Collect Asset Inventory from Windows Systems
  hosts: all
  gather_facts: true
  vars:
    output_dir: "C:\\Windows\\Temp"

  tasks:
    - name: Get CPU model
      win_shell: |
        Get-CimInstance -ClassName Win32_Processor | Select-Object -ExpandProperty Name
      register: cpu_model_output

    - name: Set CPU model fact
      set_fact:
        cpu_model: "{{ cpu_model_output.stdout_lines[0] | trim }}"

    - name: Extract processor generation (Intel only, basic logic)
      set_fact:
        cpu_generation: >-
          {% set match = cpu_model | regex_search('i[3579]-([0-9]{4,5})[A-Z]*', '\\1') %}
          {% if match|length == 5 %}
            {{ match[:2] }}th Gen
          {% elif match|length == 4 %}
            {{ match[:1] }}th Gen
          {% else %}
            Unknown
          {% endif %}

    - name: Get system serial number
      win_shell: |
        Get-CimInstance -ClassName Win32_BIOS | Select-Object -ExpandProperty SerialNumber
      register: serial_output

    - name: Set serial number fact
      set_fact:
        serial_number: "{{ serial_output.stdout | trim }}"

    - name: Get MAC address
      win_shell: |
        Get-NetAdapter | Where-Object { $_.Status -eq "Up" } | Select-Object -First 1 -ExpandProperty MacAddress
      register: mac_result

    - name: Set MAC address fact
      set_fact:
        mac_address: "{{ mac_result.stdout }}"

    - name: Gather Windows hotfixes
      win_shell: |
        Get-HotFix | Select-Object HotFixID, InstalledOn | ConvertTo-Json
      register: windows_hotfixes

    - name: Set hotfix variable
      set_fact:
        hotfix_data: "{{ windows_hotfixes.stdout | from_json }}"

    - name: Collect asset inventory
      set_fact:
        asset_data: {
          "hostname": "{{ ansible_hostname }}",
          "fqdn": "{{ ansible_fqdn | default('') }}",
          "os": "{{ ansible_distribution ~ ' ' ~ ansible_distribution_version }}",
          "kernel": "{{ ansible_kernel | default('') }}",
          "architecture": "{{ ansible_architecture | default('') }}",
          "ip_address": "{{ ansible_default_ipv4.address | default('') }}",
          "mac_address": "{{ mac_address }}",
          "cpu_cores": "{{ ansible_processor_cores | default('') }}",
          "cpu_model": "{{ cpu_model }}",
          "cpu_generation": "{{ cpu_generation }}",
          "ram_mb": "{{ ansible_memtotal_mb | default('') }}",
          "disk_info": "{{ ansible_devices | default({}) }}",
          "hotfixes": "{{ hotfix_data }}",
          "serial_number": "{{ serial_number }}"
        }

    - name: Save asset inventory to JSON
      win_copy:
        dest: "{{ output_dir }}\\asset_{{ inventory_hostname }}.json"
        content: "{{ asset_data | to_nice_json }}"
