- name: Collect Asset Inventory from All Systems
  hosts: all
  gather_facts: true
  vars:
    output_dir: "/tmp/asset_inventory"

  pre_tasks:
    - name: Ensure output directory exists (Linux only)
      when: ansible_os_family != "Windows"
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Gather Windows hotfixes (Windows only)
      when: ansible_os_family == "Windows"
      win_shell: |
        Get-HotFix | Select-Object HotFixID, InstalledOn | ConvertTo-Json
      register: windows_hotfixes

    - name: Set hotfix variable for Windows
      when: ansible_os_family == "Windows"
      set_fact:
        hotfix_data: "{{ windows_hotfixes.stdout | from_json }}"

    - name: Set empty hotfix variable for non-Windows
      when: ansible_os_family != "Windows"
      set_fact:
        hotfix_data: []

    - name: Collect asset inventory
      set_fact:
        asset_data: {
          "hostname": "{{ ansible_hostname }}",
          "fqdn": "{{ ansible_fqdn | default('') }}",
          "os": "{{ ansible_distribution ~ ' ' ~ ansible_distribution_version }}",
          "kernel": "{{ ansible_kernel | default('') }}",
          "architecture": "{{ ansible_architecture | default('') }}",
          "ip_address": "{{ ansible_default_ipv4.address | default('') }}",
          "mac_address": "{{ ansible_default_ipv4.macaddress | default('') }}",
          "cpu_cores": "{{ ansible_processor_cores | default('') }}",
          "cpu_model": "{{ ansible_processor[1] | default('') }}",
          "ram_mb": "{{ ansible_memtotal_mb | default('') }}",
          "disk_info": "{{ ansible_devices | default({}) }}",
          "hotfixes": "{{ hotfix_data }}"
        }

    - name: Save asset inventory to JSON (Linux)
      when: ansible_os_family != "Windows"
      copy:
        dest: "{{ output_dir }}/asset_{{ inventory_hostname }}.json"
        content: "{{ asset_data | to_nice_json }}"
        mode: '0644'

    - name: Save asset inventory to JSON (Windows)
      when: ansible_os_family == "Windows"
      win_copy:
        dest: "C:\\Windows\\Temp\\asset_{{ inventory_hostname }}.json"
        content: "{{ asset_data | to_nice_json }}"
