- name: Collect Asset Inventory from Linux Systems
  hosts: all
  gather_facts: true
  become: true
  vars:
    output_dir: "/tmp/asset_inventory"

  pre_tasks:
    - name: Ensure output directory exists on client
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Get CPU model
      shell: "lscpu | grep 'Model name' | awk -F: '{print $2}'"
      register: cpu_model_output
      changed_when: false

    - name: Set CPU model and generation
      set_fact:
        cpu_model: "{{ cpu_model_output.stdout | trim }}"
        cpu_generation: >-
          {% set match = cpu_model | regex_search('i[3579]-([0-9]{4,5})[A-Z]*', '\\1') %}
          {% if match is not none %}
            {% if match | length == 5 %}
              {{ match[:2] }}th Gen
            {% elif match | length == 4 %}
              {{ match[:1] }}th Gen
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Unknown
          {% endif %}

    - name: Get system serial number
      shell: "dmidecode -s system-serial-number"
      register: serial_output
      changed_when: false

    - name: Set dynamic memory facts
      set_fact:
        serial_number: "{{ serial_output.stdout | trim }}"
        mac_address: "{{ ansible_default_ipv4.macaddress | default('') }}"
        ram_mb_used: "{{ ansible_memory_mb.real.used }}"
        ram_mb_total: "{{ ansible_memory_mb.real.total }}"
        ram_used_pct: "{{ (ansible_memory_mb.real.used * 100) // ansible_memory_mb.real.total }}"

    - name: Collect asset data
      set_fact:
        asset_data: {
          "hostname": "{{ ansible_hostname }}",
          "ip_address": "{{ ansible_default_ipv4.address | default('') }}",
          "mac_address": "{{ mac_address }}",
          "cpu_model": "{{ cpu_model }}",
          "cpu_generation": "{{ cpu_generation }}",
          "ram_mb_used": "{{ ram_mb_used }}",
          "ram_mb_total": "{{ ram_mb_total }}",
          "ram_used_pct": "{{ ram_used_pct }}",
          "serial_number": "{{ serial_number }}",
          "disk_info": "{{ ansible_devices | default({}) }}",
          "os": "{{ ansible_distribution ~ ' ' ~ ansible_distribution_version }}",
          "kernel": "{{ ansible_kernel | default('') }}"
        }

    - name: Save asset inventory to JSON on client
      copy:
        dest: "{{ output_dir }}/asset_{{ inventory_hostname }}.json"
        content: "{{ asset_data | to_nice_json }}"
        mode: '0644'

    #########################################################################
    # 🔁 Fetch JSON to central exporter folder (shared with AWX Exporter)
    #########################################################################

    - name: Create folder on exporter/controller node
      delegate_to: localhost
      run_once: true
      file:
        path: /opt/awx-inventory-facts/
        state: directory
        mode: '0755'

    - name: Fetch JSON from host to exporter directory
      fetch:
        src: "{{ output_dir }}/asset_{{ inventory_hostname }}.json"
        dest: "/opt/awx-inventory-facts/"
        flat: yes
