---
- name: Collect complete asset inventory
  hosts: all
  gather_facts: yes
  become: true
  vars:
    inventory_file: "/tmp/full_inventory_{{ ansible_hostname }}.txt"

  tasks:

    - name: Ensure Python is installed (Linux only)
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      when: ansible_os_family != 'Windows'

    - name: Collect Windows hotfixes (only if ansible.windows is available)
      block:
        - name: Collect Windows hotfixes
          win_hotfix:
          register: hotfix_info

        - name: Save hotfixes to inventory file
          copy:
            dest: "{{ inventory_file }}"
            content: |
              Hostname: {{ ansible_hostname }}
              OS: {{ ansible_os_family }}
              Hotfixes:
              {% for patch in hotfix_info.hotfixes %}
              - {{ patch.HotFixID }}
              {% endfor %}
          when: hotfix_info is defined
      when: ansible_os_family == 'Windows'
      ignore_errors: yes  # To prevent failure if module is missing

    - name: Collect Linux system info
      block:
        - name: Write system info
          copy:
            dest: "{{ inventory_file }}"
            content: |
              Hostname: {{ ansible_hostname }}
              OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
              CPU: {{ ansible_processor[1] | default(ansible_processor[0] | default('N/A')) }}
              Memory: {{ ansible_memtotal_mb | default('N/A') }} MB
              Disk Info: {{ ansible_devices | default({}) | to_nice_json }}
              Installed Packages:
              {% for name, info in ansible_facts.packages | default({}) %}
              - {{ name }}: {{ info[0].version }}
              {% endfor %}
      when: ansible_os_family != 'Windows'

    - name: Print location of inventory file
      debug:
        msg: "Inventory saved to {{ inventory_file }}"
