---
- name: Collect Installed Software from Windows Systems
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get installed programs from registry and convert to YAML
      win_shell: |
        $software = Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* |
          Select-Object DisplayName, DisplayVersion, Publisher, InstallDate |
          Where-Object { $_.DisplayName }

        $structured = $software | ForEach-Object {
          [PSCustomObject]@{
            DisplayName     = $_.DisplayName
            DisplayVersion  = $_.DisplayVersion
            Publisher       = $_.Publisher
            InstallDate     = $_.InstallDate
          }
        }

        $yaml = $structured | ConvertTo-Yaml
        Set-Content -Path "C:\software_inventory.yaml" -Value $yaml -Encoding utf8
      args:
        executable: powershell.exe

    - name: Confirm YAML file created
      win_stat:
        path: "C:\software_inventory.yaml"
      register: yaml_check

    - name: Debug path of saved YAML file
      debug:
        msg: "YAML file saved at C:\\software_inventory.yaml"
      when: yaml_check.stat.exists
