- name: Collect Asset Inventory from Linux Systems
  hosts: all
  gather_facts: true
  become: true
  vars:
    output_dir: "/tmp/asset_inventory"

  pre_tasks:
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Get CPU model
      shell: "lscpu | grep 'Model name' | awk -F: '{print $2}'"
      register: cpu_model_output
      changed_when: false

    - name: Set CPU model fact
      set_fact:
        cpu_model: "{{ cpu_model_output.stdout | trim }}"

    - name: Extract processor generation (Intel only, safe logic)
      set_fact:
        cpu_generation: >-
          {% set match = cpu_model | regex_search('i[3579]-([0-9]{4,5})[A-Z]*', '\\1') %}
          {% if match is not none %}
            {% if match | length == 5 %}
              {{ match[:2] }}th Gen
            {% elif match | length == 4 %}
              {{ match[:1] }}th Gen
            {% else %}
              Unknown
            {% endif %}
          {% else %}
            Unknown
          {% endif %}

    - name: Get system serial number
      shell: "dmidecode -s system-serial-number"
      register: serial_output
      changed_when: false

    - name: Set serial number fact
      set_fact:
        serial_number: "{{ serial_output.stdout | trim }}"

    - name: Set MAC address fact
      set_fact:
        mac_address: "{{ ansible_default_ipv4.macaddress | default('') }}"

    - name: Collect asset inventory
      set_fact:
        asset_data: {
          "hostname": "{{ ansible_hostname }}",
          "fqdn": "{{ ansible_fqdn | default('') }}",
          "os": "{{ ansible_distribution ~ ' ' ~ ansible_distribution_version }}",
          "kernel": "{{ ansible_kernel | default('') }}",
          "architecture": "{{ ansible_architecture | default('') }}",
          "ip_address": "{{ ansible_default_ipv4.address | default('') }}",
          "mac_address": "{{ mac_address }}",
          "cpu_cores": "{{ ansible_processor_cores | default('') }}",
          "cpu_model": "{{ cpu_model }}",
          "cpu_generation": "{{ cpu_generation }}",
          "ram_mb": "{{ ansible_memtotal_mb | default('') }}",
          "disk_info": "{{ ansible_devices | default({}) }}",
          "hotfixes": [],
          "serial_number": "{{ serial_number }}"
        }

    - name: Save asset inventory to JSON
      copy:
        dest: "{{ output_dir }}/asset_{{ inventory_hostname }}.json"
        content: "{{ asset_data | to_nice_json }}"
        mode: '0644'
