---
- name: Disable and lock Firefox password manager on manually installed Firefox
  hosts: all
  become: yes
  tasks:

    - name: Ensure policy directory exists for Firefox 117
      file:
        path: /opt/firefox117/firefox/distribution
        state: directory
        mode: '0755'

    - name: Set Firefox policies.json with password manager disabled and locked
      copy:
        dest: /opt/firefox117/firefox/distribution/policies.json
        content: |
          {
            "policies": {
              "DisablePasswordManager": true,
              "PasswordManagerEnabled": false,
              "BlockAboutAddons": true,
              "DisableFirefoxAccounts": true
            }
          }
        mode: '0644'
