---
- name: Clear Firefox cache2 for all non-system users on Windows
  hosts: windows_clients
  gather_facts: false
  vars:
    firefox_cache_pattern: "AppData\\Local\\Mozilla\\Firefox\\Profiles\\*\\cache2"
    system_users:
      - Administrator
      - Default
      - DefaultAppPool
      - Public
      - All Users
      - desktop.ini
      - defaultuser0
      - elastic-agent-user
  tasks:

    - name: Get list of all user directories in C:\Users
      win_find:
        paths: 'C:\Users'
        file_type: directory
        depth: 1
      register: user_dirs

    - name: Extract usernames from folder paths
      set_fact:
        all_usernames: "{{ user_dirs.files | map(attribute='path') | map('basename') | list }}"

    - name: Filter out system users
      set_fact:
        valid_users: "{{ all_usernames | difference(system_users) }}"

    - name: Construct full user paths
      set_fact:
        valid_user_paths: "{{ valid_users | map('regex_replace', '^(.*)$', 'C:\\\\Users\\\\\\1') | list }}"

    - name: Show filtered valid_user_paths
      debug:
        var: valid_user_paths

    - name: Find all Firefox cache2 folders for each valid user
      win_find:
        paths: "{{ item }}\\{{ firefox_cache_pattern }}"
        file_type: directory
      loop: "{{ valid_user_paths }}"
      register: firefox_cache_dirs
      ignore_errors: yes

    - name: Flatten found Firefox cache2 paths
      set_fact:
        all_firefox_cache2_paths: "{{ firefox_cache_dirs.results | map(attribute='files') | sum(start=[]) | map(attribute='path') | list }}"

    - name: Delete entire Firefox 'cache2' folders
      win_file:
        path: "{{ item }}"
        state: absent
      loop: "{{ all_firefox_cache2_paths }}"

    - name: (Optional) Recreate empty 'cache2' folder after cleanup
      win_file:
        path: "{{ item }}"
        state: directory
      loop: "{{ all_firefox_cache2_paths }}"
