---
- name: Clear Chrome and Firefox cache for all users
  hosts: windows
  gather_facts: false
  tasks:

    - name: Get all user folders
      win_find:
        paths: C:\Users
        file_type: directory
      register: user_dirs

    - name: Filter valid user profiles (skip system folders)
      set_fact:
        valid_users: >-
          {{
            user_dirs.files
            | map(attribute='path')
            | select('match', '^C:\\\\Users\\\\(?!Public|Default|All Users|Default User|defaultuser0|WDAGUtilityAccount).*')
            | list
          }}

    - name: Kill Firefox process to unlock cache
      win_shell: taskkill /F /IM firefox.exe
      ignore_errors: true

    - name: Clear Chrome cache for all users
      win_file:
        path: "{{ item }}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache"
        state: absent
      loop: "{{ valid_users }}"

    - name: Find Firefox cache2 folders
      win_find:
        paths: "{{ item }}\\AppData\\Local\\Mozilla\\Firefox\\Profiles"
        patterns: "cache2"
        file_type: directory
      register: firefox_cache_folders
      loop: "{{ valid_users }}"
      loop_control:
        label: "{{ item }}"

    - name: Delete 'entries' folder inside Firefox cache2
      win_file:
        path: "{{ item.path }}\\entries"
        state: absent
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined

    - name: Recreate empty 'entries' folder (optional)
      win_file:
        path: "{{ item.path }}\\entries"
        state: directory
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined
