---
- name: Clear Chrome and Firefox cache for all users
  hosts: windows
  gather_facts: false

  vars:
    skip_users: 
      - Public
      - Default
      - All Users
      - Default User
      - defaultuser0
      - WDAGUtilityAccount
      - Administrator
      - DefaultAppPool
      - elastic-agent-user

  tasks:

    - name: Get all user folders
      win_find:
        paths: C:\Users
        file_type: directory
      register: user_dirs

    - name: Filter valid user profiles (skip system folders)
      set_fact:
        valid_users: >-
          {{
            user_dirs.files
            | map(attribute='path')
            | reject('search', 'C:\\\\Users\\\\(' + skip_users | join('|') + ')$')
            | list
          }}

    - name: Debug valid user list
      debug:
        var: valid_users

    - name: Clear Chrome cache for all users
      win_file:
        path: "{{ item }}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache"
        state: absent
      loop: "{{ valid_users }}"

    - name: Find all Firefox cache2 folders under each user
      win_find:
        paths: "{{ item }}\\AppData\\Local\\Mozilla\\Firefox\\Profiles"
        patterns: cache2
        recurse: true
        file_type: directory
      loop: "{{ valid_users }}"
      loop_control:
        label: "{{ item }}"
      register: firefox_cache_folders

    - name: Delete entire Firefox 'cache2' folders
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined

    - name: (Optional) Recreate empty 'cache2' folders after cleanup
      win_file:
        path: "{{ item.path }}"
        state: directory
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined
