---
- name: Clear Chrome and Firefox cache for all users
  hosts: windows
  gather_facts: false

  tasks:

    - name: Get all user folders
      win_find:
        paths: C:\Users
        file_type: directory
      register: user_dirs

    - name: Show user_dirs found under C:\Users
      debug:
        var: user_dirs.files

    - name: Filter valid user profiles (skip system folders)
      set_fact:
        valid_users: >-
          {{
            user_dirs.files
            | map(attribute='path')
            | select('match', '^C:\\\\Users\\\\(?!Public$|Default$|All Users$|Default User$|defaultuser0$|WDAGUtilityAccount$).*')
            | list
          }}

    - name: Show filtered valid_users
      debug:
        var: valid_users

    - name: Clear Chrome cache for all users
      win_file:
        path: "{{ item }}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache"
        state: absent
      loop: "{{ valid_users }}"
      loop_control:
        label: "{{ item }}"

    - name: Find all Firefox cache2 folders under each user
      win_find:
        paths: "{{ item }}\\AppData\\Local\\Mozilla\\Firefox\\Profiles"
        patterns: cache2
        recurse: true
        file_type: directory
      loop: "{{ valid_users }}"
      loop_control:
        label: "{{ item }}"
      register: firefox_cache_folders

    - name: Delete entire Firefox 'cache2' folders
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined
      loop_control:
        label: "{{ item.path }}"

    - name: (Optional) Recreate empty 'cache2' folder after cleanup
      win_file:
        path: "{{ item.path }}"
        state: directory
      loop: "{{ firefox_cache_folders.results | map(attribute='files') | sum(start=[]) }}"
      when: item.path is defined
      loop_control:
        label: "{{ item.path }}"
