---
- name: Clear Chrome and Firefox cache for all users
  hosts: windows
  gather_facts: false

  tasks:

    - name: Get all user folders
      win_find:
        paths: C:\Users
        file_type: directory
      register: user_dirs

    - name: Filter valid user profiles (skip system folders)
      set_fact:
        valid_users: >
          {{ user_dirs.files
             | rejectattr('path', 'search', 'Default')
             | rejectattr('path', 'search', 'Public')
             | rejectattr('path', 'search', 'All Users')
             | rejectattr('path', 'search', 'Administrator')
             | map(attribute='path') | list }}

    - name: Kill Firefox if running
      win_shell: Stop-Process -Name firefox -Force
      ignore_errors: yes

    - name: Clear Chrome cache for all users
      win_file:
        path: "{{ item }}\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache"
        state: absent
      loop: "{{ valid_users }}"

    - name: Find Firefox cache2/entries directories
      win_find:
        paths: "{{ item }}\\AppData\\Local\\Mozilla\\Firefox\\Profiles"
        patterns: entries
        file_type: directory
        recurse: yes
      loop: "{{ valid_users }}"
      loop_control:
        label: "{{ item }}"
      register: ff_cache_entries

    - name: Remove all Firefox cache2/entries directories found
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ ff_cache_entries.results | map(attribute='files') | sum(start=[]) }}"
