---
- name: Detect Linux OS End of Life (EOL) Status
  hosts: linux_servers
  gather_facts: yes
  become: false
  vars:
    ubuntu_eol_dates:
      trusty: "2019-04-30"
      xenial: "2021-04-30"
      bionic: "2023-04-30"
      focal: "2025-04-30"
      jammy: "2027-04-30"
      noble: "2029-04-30"

    mint_eol_dates:
      uma: "2025-07-31"
      una: "2023-07-31"
      xia: "Unknown"  # Example; update if Mint publishes official EOL

  tasks:
    - name: Detect OS details
      set_fact:
        distro: "{{ ansible_distribution }}"
        version: "{{ ansible_distribution_version }}"
        codename: "{{ ansible_lsb.codename | default('Unknown') }}"

    - name: Determine EOL date
      set_fact:
        eol_date: >-
          {% if distro == 'Ubuntu' %}
          {{ ubuntu_eol_dates.get(codename, 'Unknown') }}
          {% elif distro == 'LinuxMint' %}
          {{ mint_eol_dates.get(codename, 'Unknown') }}
          {% else %}
          Unknown
          {% endif %}

    - name: Determine EOL status
      set_fact:
        eol_status: >-
          {% if eol_date == 'Unknown' %}
          Unknown
          {% elif (ansible_date_time.date | to_datetime('%Y-%m-%d')) > (eol_date | trim | to_datetime('%Y-%m-%d')) %}
          EOL - Upgrade Required!
          {% else %}
          Supported until {{ eol_date }}
          {% endif %}

    - name: Save EOL status to hostvars
      set_fact:
        eol_summary:
          os: "{{ distro }} {{ version }}"
          codename: "{{ codename }}"
          eol_date: "{{ eol_date }}"
          status: "{{ eol_status }}"

    - name: Debug per-host EOL status
      debug:
        msg: "Host {{ inventory_hostname }} → OS: {{ distro }} {{ version }} ({{ codename }}), Status: {{ eol_status }}"
