---
- name: Detect Linux OS End of Life (EOL) Status
  hosts: Tirumangalam
  gather_facts: yes
  become: false
  vars:
    # Example EOL lookup table (update as needed)
    ubuntu_eol_dates:
      trusty: "2019-04-30"
      xenial: "2021-04-30"
      bionic: "2023-04-30"
      focal: "2025-04-30"
      jammy: "2027-04-30"
      noble: "2029-04-30"
    mint_eol_dates:
      uma: "2025-07-31"
      una: "2023-07-31"
      xia: "Unknown"  # Example; update as needed

  tasks:

    - name: Detect OS details
      set_fact:
        distro: "{{ ansible_distribution }}"
        version: "{{ ansible_distribution_version }}"
        codename: "{{ ansible_lsb.codename | default('Unknown') }}"

    - name: Determine EOL date
      set_fact:
        eol_date: >-
          {% if distro == 'Ubuntu' %}
          {{ ubuntu_eol_dates.get(codename, 'Unknown') }}
          {% elif distro == 'LinuxMint' %}
          {{ mint_eol_dates.get(codename, 'Unknown') }}
          {% else %}
          Unknown
          {% endif %}
        eol_status: >-
          {% if eol_date == 'Unknown' %}
          Unknown
          {% elif (ansible_date_time.date | to_datetime('%Y-%m-%d')) > (eol_date | to_datetime('%Y-%m-%d')) %}
          EOL - Upgrade Required!
          {% else %}
          Supported
          {% endif %}

    - name: Save EOL status to hostvars
      set_fact:
        eol_summary:
          os: "{{ distro }} {{ version }}"
          codename: "{{ codename }}"
          eol_date: "{{ eol_date }}"
          status: "{{ eol_status }}"

    - name: Debug per-host EOL status
      debug:
        msg: "EOL Status: {{ eol_status }}"

- name: Consolidate Linux EOL report
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build consolidated EOL report
      run_once: true
      set_fact:
        consolidated_report: |
          | Hostname/IP | OS | Codename | EOL Date | Status |
          |-------------|----|----------|----------|--------|
          {% for host in groups['linux_servers'] %}
          | {{ host }} | {{ hostvars[host].eol_summary.os | default('Unknown') }} | {{ hostvars[host].eol_summary.codename | default('Unknown') }} | {{ hostvars[host].eol_summary.eol_date | default('Unknown') }} | {{ hostvars[host].eol_summary.status | default('⚠️ Unreachable') }} |
          {% endfor %}

    - name: Print consolidated EOL report
      debug:
        msg: "{{ consolidated_report }}"
