- name: Disable Firefox password manager visibly in policies UI
  hosts: kali_linux
  become: true
  tasks:
    - name: Ensure Firefox policy directory exists
      ansible.builtin.file:
        path: /usr/lib/firefox-esr/distribution
        state: directory
        mode: '0755'

    - name: Set Firefox policies.json with visible password manager disable policy
      ansible.builtin.copy:
        dest: /usr/lib/firefox-esr/distribution/policies.json
        content: |
          {
            "policies": {
              "DisablePasswordManager": true,
              "DisplayBookmarksToolbar": true,
              "NoDefaultBookmarks": true,
              "OverrideFirstRunPage": "",
              "OverridePostUpdatePage": "",
              "Homepage": {
                "URL": "file:///usr/share/kali-defaults/web/homepage.html",
                "Locked": false,
                "StartPage": "homepage"
              },
              "DisableTelemetry": true,
              "NetworkPrediction": false,
              "DNSOverHTTPS": {
                "Enabled": false
              },
              "CaptivePortal": false,
              "FirefoxHome": {
                "Search": true,
                "TopSites": true,
                "Highlights": false,
                "Pocket": false,
                "Snippets": false,
                "Locked": false
              }
            }
          }
        mode: '0644'
