- name: Append Firefox policies on Cinnamon Linux safely (no external collections)
  hosts: cinnamon
  become: true
  vars:
    policies_file: /usr/lib/firefox/distribution/policies.json
  tasks:

    - name: Ensure Firefox distribution directory exists
      ansible.builtin.file:
        path: /usr/lib/firefox/distribution
        state: directory
        mode: '0755'

    - name: Create a base policies.json if not present
      ansible.builtin.shell: |
        if [ ! -f "{{ policies_file }}" ]; then
          echo '{"policies":{}}' > "{{ policies_file }}"
        fi

    - name: Append new Firefox policies using jq
      ansible.builtin.shell: |
        jq '.policies += {
          "BlockAboutConfig": true,
          "DisableSetDesktopBackground": true,
          "PasswordManagerEnabled": false,
          "SyncDisabled": true
        }' "{{ policies_file }}" > /tmp/policies.json && mv /tmp/policies.json "{{ policies_file }}"
      args:
        executable: /bin/bash
