- name: Append Firefox policies on Linux systems
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Only run on Linux
      ansible.builtin.assert:
        that: ansible_os_family != 'Windows'
        fail_msg: "This playbook should only run on Linux hosts."
        success_msg: "Host is Linux. Proceeding."

    - name: Ensure Firefox policy directory exists
      ansible.builtin.file:
        path: /usr/lib/firefox/distribution
        state: directory
        mode: '0755'

    - name: Ensure policies.json file exists
      ansible.builtin.copy:
        dest: /usr/lib/firefox/distribution/policies.json
        content: |
          {
            "policies": {
              "BlockAboutConfig": true,
              "DisableSetDesktopBackground": true,
              "PasswordManagerEnabled": false,
              "SyncDisabled": true
            }
          }
        mode: '0644'
        force: false
