---
- name: Enforce Firefox 117 permanently and auto-revert on change
  hosts: windows
  gather_facts: yes
  vars:
    firefox_version: "117.0"
    firefox_download_url: "https://archive.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe"
    firefox_install_dir: "C:\\Program Files\\Mozilla Firefox"
    temp_dir: "C:\\temp"
    check_script_path: "C:\\ProgramData\\CheckFirefox.ps1"
    installer_path: "{{ temp_dir }}\\Firefox_Setup_117.0.exe"

  tasks:

    - name: Create temp folder
      ansible.windows.win_file:
        path: "{{ temp_dir }}"
        state: directory

    - name: Download Firefox 117 installer
      ansible.windows.win_get_url:
        url: "{{ firefox_download_url }}"
        dest: "{{ installer_path }}"

    - name: Install Firefox 117 silently
      ansible.windows.win_package:
        path: "{{ installer_path }}"
        arguments: "/S"
        state: present
        wait_for_children: yes

    - name: Ensure Firefox distribution folder exists
      ansible.windows.win_file:
        path: "{{ firefox_install_dir }}\\distribution"
        state: directory

    - name: Lock Firefox updates via policies.json
      ansible.windows.win_copy:
        dest: "{{ firefox_install_dir }}\\distribution\\policies.json"
        content: |
          {
            "policies": {
              "DisableAppUpdate": true
            }
          }

    - name: Disable Firefox updates via registry
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Mozilla\Firefox
        name: DisableAppUpdate
        data: 1
        type: dword

    - name: Create PowerShell script to auto-revert Firefox if version changes
      ansible.windows.win_copy:
        dest: "{{ check_script_path }}"
        content: |
          $path = "C:\Program Files\Mozilla Firefox\firefox.exe"
          if (Test-Path $path) {
              $installed = (Get-Item $path).VersionInfo.ProductVersion
              if ($installed -notlike "{{ firefox_version }}*") {
                  Start-Process "C:\Program Files\Mozilla Firefox\uninstall\helper.exe" -ArgumentList "/S" -Wait
                  Start-Sleep -Seconds 5
                  Start-Process "{{ installer_path }}" -ArgumentList "/S" -Wait
              }
          }

    - name: Create scheduled task via PowerShell (to enforce version at boot)
      ansible.windows.win_shell: |
        $exists = Get-ScheduledTask -TaskName "CheckFirefoxVersion" -ErrorAction SilentlyContinue
        if (-not $exists) {
            $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-ExecutionPolicy Bypass -File '{{ check_script_path }}'"
            $trigger = New-ScheduledTaskTrigger -AtStartup
            $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest
            $task = New-ScheduledTask -Action $action -Trigger $trigger -Principal $principal
            Register-ScheduledTask -TaskName "CheckFirefoxVersion" -InputObject $task -Force
        }

    - name: Remove Firefox installer to clean up
      ansible.windows.win_file:
        path: "{{ installer_path }}"
        state: absent
