- name: Append Firefox policies on Cinnamon Linux safely (no external collections)
  hosts: cinnamon_ubuntu
  become: true
  gather_facts: true
  tasks:

    - name: Create Firefox distribution directory if not exists
      ansible.builtin.file:
        path: /usr/lib/firefox/distribution
        state: directory
        mode: '0755'

    - name: Append or create Firefox policies.json (overwrite with merged values)
      ansible.builtin.copy:
        dest: /usr/lib/firefox/distribution/policies.json
        content: |
          {
            "policies": {
              "BlockAboutConfig": true,
              "DisableSetDesktopBackground": true,
              "PasswordManagerEnabled": false,
              "SyncDisabled": true
            }
          }
        mode: '0644'
