---
- name: Append Firefox policies on Cinnamon Linux safely (no external collections)
  hosts: cinnamon_ubuntu   # 🟢 This must exactly match your inventory
  become: true
  tasks:

    - name: Ensure policies.json file exists
      ansible.builtin.file:
        path: /usr/lib/firefox/distribution/policies.json
        state: touch
        mode: '0644'

    - name: Append Firefox policies with win_shell fallback
      ansible.builtin.copy:
        dest: /usr/lib/firefox/distribution/policies.json
        content: |
          {
            "policies": {
              "BlockAboutConfig": true,
              "DisableSetDesktopBackground": true,
              "PasswordManagerEnabled": false,
              "SyncDisabled": true
            }
          }
        mode: '0644'
